### ISSUE TITLE
ClassNotFound exception

### ISSUE THREAD

**Issue by arunturo** [kafbat/ui-serde-glue#2]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/SECURITY.md)

### Describe the bug (actual behavior)

I ran the kafbat kafka-ui as specified in the following docker-compose [example file](https://github.com/kafbat/ui-serde-glue/blob/main/docker-compose/setup-example.yaml).

The only thing I tweaked is, I downloaded the jar file https://github.com/kafbat/ui-serde-glue/releases/download/1.0.0/kafkaui-glue-serde-1.0.0-jar-with-dependencies.jar and placed it in the  volume mount path`/glue-serde`.

When the application comes up, it fails with the following error

```
kafka-ui      | 	... 42 common frames omitted
kafka-ui      | Caused by: java.lang.ClassNotFoundException: com.provectus.kafka.ui.serde.api.Serde
kafka-ui      | 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
kafka-ui      | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
kafka-ui      | 	at io.kafbat.ui.serdes.CustomSerdeLoader$ChildFirstClassloader.loadClass(CustomSerdeLoader.java:122)
kafka-ui      | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
kafka-ui      | 	... 63 common frames omitted
```
I believe, this is due to referencing `com.provectus.kafka.ui.serde.api.Serde` instead of referencing the kafbat version of this class file at https://github.com/kafbat/kafka-ui/blob/main/serde-api/src/main/java/io/kafbat/ui/serde/api/Serde.java.

### Expected behavior

The application should run succesfully without any errors.

### Your installation details

I used the following docker-compose.yml file to run the application

version: '2'
services:

  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper0
      - kafka0
    environment:
      # you can specify aws creds globally. Optional.
      AWS_ACCESS_KEY_ID: '{ AWS_ACCESS_KEY_ID }'
      AWS_SECRET_ACCESS_KEY: '{ AWS_SECRET_ACCESS_KEY }'

      kafka.clusters.0.name: MyFavoriteCluster
      kafka.clusters.0.bootstrapServers: kafka0:29092

      kafka.clusters.0.serde.0.name: GlueSchemaRegistry
      kafka.clusters.0.serde.0.filePath: /glue-serde/kafkaui-glue-serde-1.0.0-jar-with-dependencies.jar
      kafka.clusters.0.serde.0.className: com.provectus.kafka.ui.serdes.glue.GlueSerde
      kafka.clusters.0.serde.0.properties.region: us-east-1  #required
      kafka.clusters.0.serde.0.properties.registry: kui-test #required, name of Glue Schema Registry
      # template that will be used to find schema name for topic key. Optional, default is null (not set).
      kafka.clusters.0.serde.0.properties.keySchemaNameTemplate: "%s-key"
      # template that will be used to find schema name for topic value. Optional, default is  '%s'
      kafka.clusters.0.serde.0.properties.valueSchemaNameTemplate: "%s-value"
      # schema name -> topics pattern where it will be used for keys. Optional.
      kafka.clusters.0.serde.0.properties.topicKeysSchemas.some-topic-key: "some-topic1|some-topic2"
      # schema name -> topics pattern where it will be used for values. Optional.
      kafka.clusters.0.serde.0.properties.topicValuesSchemas.some-topic-value: "some-topic1|some-topic2"
      kafka.clusters.0.serde.0.properties.topicValuesSchemas.another-topic-val: "another-topic-value"

      # you can explicitly specify aws creds on serde level (not globally, Optional.):
      # by providing access keys:
      kafka.clusters.0.serde.0.properties.awsAccessKeyId:  '{ AWS_ACCESS_KEY_ID }'
      kafka.clusters.0.serde.0.properties.awsSecretAccessKey:  '{ AWS_SECRET_ACCESS_KEY }'
      # or by using profile path properties:
      kafka.clusters.0.serde.0.properties.awsProfileName: '{ profile which will be looked in profile file, "default" by default}'
      kafka.clusters.0.serde.0.properties.awsProfileFile: '{ path to profile path, "~/.aws/credentials" by default }'

    volumes:
      - ./:/glue-serde

  zookeeper0:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka0:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper0
    ports:
      - 9092:9092
      - 9997:9997
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

### Steps to reproduce

1. Download the https://github.com/kafbat/ui-serde-glue/releases/download/1.0.0/kafkaui-glue-serde-1.0.0-jar-with-dependencies.jar and place it in the same folder as that of the docker-compose file.
2. Ensure the volumes mounted reflect the following path. The jar file is in the same folder as that of docker-compose.yml file and the jar file is thus available to the application container at the `glue-serde` path.
   volumes:
      - ./:/glue-serde
3. docker-compose up

### Logs

redacted

**Comment by Haarolean** [comment]
@arunturo 

could you please try this jar?
https://stash.haarolean.dev/s/YJLeupQ
Let me know how it goes.
`kafka.clusters.0.serde.0.className: io.kafbat.ui.serde.glue.GlueSerde`

**Comment by arunturo** [comment]
Hi @Haarolean ,

 Thank you for the quick turn around. That resolved the problem. I was able to use AWS Glue registry to decode the message in the topic. 

Will there be a official release of the fix?

I am new to the tool and generally to Kafka as well. Is there anything else I should expect from the Kafbat-UI in regards to AWS Glue integration? Like browsing the schemas etc...or is it limited to serializing/deserializing the messages in the topic.

**Comment by Haarolean** [comment]
@arunturo cool, glad it worked. We'll merge this soon and release a minor version of the serde, but you're free to use the jar I've provided.

Yeah, basically it's just (de-)serializing the messages, there's no SR integration as we expect you to do that in AWS directly.

**Comment by brianpham** [comment]
@Haarolean I work with @arunturo and I am testing with using 1.0.1 and 1.1.0 and running into issues with it starting still. This si what I see in the log. I was trying to download the jar you shared above, but its no longer available.  

```Caused by: java.lang.IllegalStateException: Location does not exist
	at io.kafbat.ui.serdes.CustomSerdeLoader.createClassloader(CustomSerdeLoader.java:81) ~[!/:v1.4.2]
	at io.kafbat.ui.serdes.CustomSerdeLoader.loadAndConfigure(CustomSerdeLoader.java:42) ~[!/:v1.4.2]
	at io.kafbat.ui.serdes.SerdesInitializer.loadAndInitCustomSerde(SerdesInitializer.java:289) ~[!/:v1.4.2]
	at io.kafbat.ui.serdes.SerdesInitializer.createSerdeFromConfig(SerdesInitializer.java:210) ~[!/:v1.4.2]
	at io.kafbat.ui.serdes.SerdesInitializer.init(SerdesInitializer.java:113) ~[!/:v1.4.2]
	at io.kafbat.ui.service.DeserializationService.<init>(DeserializationService.java:40) ~[!/:v1.4.2]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210) ~[spring-beans-6.2.12.jar!/:6.2.12]
	... 53 common frames omitted```

**Comment by brianpham** [comment]
Oh nvm, I found the issue was in the application.yaml conf. Thank you!
